service: wtexp-log-delay

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: test

functions:
  hello:
    handler: handler-wrapper.hello
    events:
      - http:
          path: microbmark
          method: get

  ########################################
  ## Watchtower Functions
  ##
  ##
  ##   Log Ingestion Dummy
  watchtower-ingestion:
    handler: ingestion.handler
    events:
    - cloudwatchLog:
        logGroup: /aws/lambda/wtexp-log-delay-${self:provider.stage}-hello
        filter: '"#####EVENTUPDATE"'
  ##
  ## END of Watchtower Functions
  ########################################
