service: wtexp-rec-oh

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: test

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: microbmark
          method: get
